import = ["~/.config/alacritty/one_dark.toml"]

[shell]
program = "zsh"

[window]
dimensions = { columns = 110, lines = 30 }
padding = { x = 12, y = 12 }
dynamic_padding = true

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
size = 11.25

[cursor]
style = { shape = "Beam", blinking = "On" }